### ISSUE TITLE
dva-native git XX 图片资源损坏

### ISSUE THREAD

**Issue by dagouzhi** [danmin25/dva-native-cli#1]
`$ dva-native git test`
git 拉取下来的图片资源损坏
建议删除.git文件夹信息
文件： 

- /app/images/house.png

           

- /app/images/person.png

**Comment by danmin25** [comment]
bug已修复，删除.git和图片资源损坏问题

**Comment by chang-ke** [comment]
@hexiao-o bug已修复，删除.git和图片资源损坏问题
