### ISSUE TITLE
Please upgrade your code to use `jumpTo` warning

### ISSUE THREAD

**Issue by davidzhang12138** [danmin25/dva-native-cli#2]
console.warn(
      'Method `jumpToIndex` is deprecated. Please upgrade your code to use `jumpTo` instead.',
      `Change your code from \`jumpToIndex(${index})\` to \`jumpTo('${key}').\``
    );

"react": "16.3.1",
"react-native": "0.55.4",
"react-navigation": "^2.0.4",

**Comment by chang-ke** [comment]
@davidzhang12138  This warning is related to react-navigation，it's mean jumpToIndexshould replace by jumpTo。for more information [issue](https://github.com/react-navigation/react-navigation/issues/4362)
